/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaproject;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void sayHello(String name){
        System.out.println("Hello " + name);
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        sayHello("Jhon");
        sayHello("world");
    }
}
